### ISSUE TITLE
[Bug]: Missing dependency: aws-amplify

### ISSUE THREAD

**Issue by JoanBogunya** [iavofficial/IAVFrontendFramework#18]
### Summary

The package has a dependency (aws-amplify) that's not installed and it's causing it to not work

### Framework version

1.0.0

### Steps to reproduce

1. Install the package
2. Try to run the application

### What is the current bug behavior?

The application does not work

### What is the expected correct behavior?

The package should have all dependencies in its package.json

### Relevant logs and/or screenshots

![image](https://github.com/user-attachments/assets/9f4f109a-1d0c-4a8d-963a-b50abe564cc5)

**Comment by mikewegele** [comment]
Thank you for your message!
In order to use the library, you need to install aws-amplify manually.
We will adapt the documentation so that the developer has to install the corresponding libraries himself.

**Comment by dahelfi** [comment]
Hello JoanBogunya, 

the issue you're encountering is due to using a version of the Amplify package that is older than version 6. AWS introduced many changes in the breaking change from version 5 to 6, including modifications to the import structure of various functions. To resolve this issue, you need to install and use Amplify version 6 in your project.

Nontheless we will add a hint in the documentation, that the usage of the AWSAuthentication System is only possible after the installation of the latest Amplfiy Package.
